### ISSUE TITLE
No transparency in non-active splits

### ISSUE THREAD

**Issue by ianrmhill** [tribela/vim-transparent#10]
Hello, great plugin! One thing I still have to set manually to get full transparency is 'hi NormalNC guibg=NONE ctermbg=NONE' in order to have non-active splits retain their transparency.

To fix within vim-transparent I added NormalNC to the transparent_groups list, but should check that this solution works generally, I'm using neovim within WSL2 within Windows Terminal.

**Comment by tribela** [comment]
Thank you for using this plugin.
If you don't mind, Make a patch and PR please?
Or, I could add it

**Comment by ianrmhill** [comment]
I can make a patch! Let me first check that the added parameter doesn't cause issues in standard vim, as it looks like the NormalNC flag is exclusive to neovim.

**Comment by ianrmhill** [comment]
Merged PR fixes issue in my environment, closing this issue. Can reopen if someone encounters issues in a specific environment due to the change.
