### ISSUE TITLE
Error detected while processing function "function background#toggle"

### ISSUE THREAD

**Issue by JGSphaela** [tribela/vim-transparent#9]
Hi, I try to use the `:TransparentToggle` and get the error below:
```
function background#toggle の処理中にエラーが検出されました:
行    2:
E121: Undefined variable: g:colors_name
```
I'm running nvim on Arch Linux. Via Vim-Plug

**Comment by tribela** [comment]
Maybe you don't set the colour theme?
Thanks for reporting. I'll fix it later
